---
title: "Environmental Variable Raster Stack"
subtitle: "Using a function to create prediction rasters for all plots"
author: "Briana Barajas"
date: 2024-020-12
---

```{r packages, include=FALSE}
# wrangling
library(tidyverse)
library(here)
library(janitor)

# raster/geospatial
library(sf)
library(tmap)
library(terra)
library(raster)
library(spatialEco) #transform elev to hli

# set data directory
data_dir <- here("data", "CampRoberts_spatial_data")
output_dir <- here("data", "updated-rasters")
```

## Create Function for Raster Manipulation

```{r}
createPredStack <- function(plot_number, new_crs = "WGS84", path){
  
  ## ========================================
  ##            Read in Data            ----
  ## ========================================
  
  # point data ----
  occurence <- st_read(here(data_dir, "Species_pts",
                            "CR_BASP_obs_11Jul22.shp")) %>% 
    clean_names() %>% 
    st_make_valid() %>% 
    filter(plot == plot_number)
  
  # plot outline ----
  outline <- st_read(here(data_dir, "plot_outlines", 
                          paste0("Plot_", plot_number, ".shp"))) %>%
    st_make_valid()
  
  # geomorphology rasters ----
  slope <- rast(here(data_dir, "old", "crob_slope"))
  elev <- rast(here(data_dir, "crob_elev"))
  
  # create hli raster ----
  hli <-  hli(elev)
  
  # vegetation rasters ----
  canopy <- rast(here(data_dir, "Canopy_raster",
                      paste0("can_fx_3r_p", plot_number)))
  
  dnd_dn <- rast(here(data_dir, "brush_IDW3rad",
                      paste0("3rd_dnd_dn_p", plot_number)))
  
  li_dn <- rast(here(data_dir, "brush_IDW3rad",
                     paste0("3rd_li_dn_p", plot_number)))
  
  gs_dn <- rast(here(data_dir, "brush_IDW3rad",
                     paste0("3rd_gs_dn_p", plot_number)))
  
  # new vegetation rasters (2024-04) ----
  ba_dn <- rast(here(data_dir, "brush_IDW3rad", 
                     paste0("3rd_ba_dn_p", plot_number)))
  br_dn <- rast(here(data_dir, "brush_IDW3rad", 
                     paste0("3rd_br_dn_p", plot_number)))
  br_ht <- rast(here(data_dir, "brush_IDW3rad", 
                     paste0("3rd_br_ht_p", plot_number)))
  # dnd_db <- rast(here(data_dir, "brush_IDW3rad", 
  #                     paste0("3rd_dnd_db_p", plot_number)))
  dnd_st <- rast(here(data_dir, "brush_IDW3rad", 
                      paste0("3rd_dnd_st_p", plot_number)))
  fb_dn <- rast(here(data_dir, "brush_IDW3rad", 
                     paste0("3rd_fb_dn_p", plot_number)))
  rk_dn <- rast(here(data_dir, "brush_IDW3rad", 
                     paste0("3rd_rk_dn_p", plot_number)))
  dnd_stc <- rast(here(data_dir, "brush_IDW3rad", 
                       paste0("dnd_stc_3rp", plot_number)))
  
  
  ## ========================================
  ##            Reproject Data           ----
  ## ========================================
  
  # reproject occurrence points ----
  occurence <- st_transform(occurence, crs = new_crs)
  
  # reproject plot outline ----
  outline <- st_transform(outline, crs = new_crs)
  
  # geomorphology rast reprojection ----
  elev <- project(elev, y = new_crs)
  slope <- project(slope, y = new_crs)
  hli <- project(hli, y = new_crs)
  
  # veg rast reprojection ----
  canopy <- project(x = canopy, y = new_crs)
  dnd_dn <- project(x = dnd_dn, y = new_crs)
  li_dn <- project(x = li_dn, y = new_crs)
  gs_dn <- project(x = gs_dn, y = new_crs)
  
  ba_dn <- project(x = ba_dn, y = new_crs)
  br_dn <- project(x = br_dn, y = new_crs)
  br_ht <- project(x = br_ht, y = new_crs)
  # dnd_db <- project(x = dnd_db, y = new_crs)
  dnd_st <- project(x = dnd_st, y = new_crs)
  fb_dn <- project(x = fb_dn, y = new_crs)
  rk_dn <- project(x = rk_dn, y = new_crs)
  dnd_stc <- project(x = dnd_stc, y = new_crs)
  
  # update raster names ----
  set.names(elev, "elevation")
  set.names(hli, "heat_load_index")
  set.names(slope, "slope")
  set.names(canopy, "canopy_cover")
  set.names(dnd_dn, "downed_wood_cover")
  set.names(li_dn, "litter_cover")
  set.names(gs_dn, "grass_cover")
  
  set.names(ba_dn, "ba_dn")
  set.names(br_dn, "br_dn")
  set.names(br_ht, "br_ht")
  set.names(dnd_st, "dnd_st")
  set.names(dnd_stc, "dnd_stc")
  set.names(fb_dn, "fb_dn")
  set.names(rk_dn, "rk_dn")
  
  ## ========================================
  ##           Update ext and res        ----
  ## ========================================
  
  # save extent ----
  can_extent <- ext(canopy)
  
  # crop geomorphology rasters ----
  elev <- crop(elev, canopy)
  hli <- crop(hli, canopy)
  slope <- crop(slope, canopy)
  
  # update geo raster ext ----
  ext(elev) <- c(can_extent$xmin, can_extent$xmax,
                 can_extent$ymin, can_extent$ymax)
  
  ext(hli) <- c(can_extent$xmin, can_extent$xmax,
                can_extent$ymin, can_extent$ymax)
  
  ext(slope) <- c(can_extent$xmin, can_extent$xmax,
                  can_extent$ymin, can_extent$ymax)
  
  # update resolution in all geomorphic layers ----
  elev <- resample(elev, canopy)
  hli <- resample(hli, canopy)
  slope <- resample(slope, canopy)
  
  ## ========================================
  ##            Export Veg Rasters       ----
  ## ========================================
  # export canopy raster ----
  writeRaster(x = canopy, gdal="COMPRESS=NONE",
              filename = paste0(path, "/canopy/plot",
                                plot_number, "/canopy.asc"), overwrite=TRUE)
  
  # export downed-wood raster ----
  writeRaster(x = dnd_dn, gdal="COMPRESS=NONE",
              filename = paste0(path, "/dnd_dn/plot",
                                plot_number, "/dnd_dn.asc"), overwrite=TRUE)
  
  # export litter cover raster ----
  writeRaster(x = li_dn, gdal="COMPRESS=NONE",
              filename = paste0(path, "/li_dn/plot",
                                plot_number, "/li_dn.asc"), overwrite=TRUE)
  
  # export grass cover raster ----
  writeRaster(x = gs_dn, gdal="COMPRESS=NONE",
              filename = paste0(path, "/gs_dn/plot",
                                plot_number, "/gs_dn.asc"), overwrite=TRUE)
  
  # export added veg rasters (2024-04) ----
  writeRaster(x = ba_dn, gdal="COMPRESS=NONE",
              filename = paste0(path, "/ba_dn/plot",
                                plot_number, "/ba_dn.asc"), overwrite=TRUE)
  writeRaster(x = br_dn, gdal="COMPRESS=NONE",
              filename = paste0(path, "/br_dn/plot",
                                plot_number, "/br_dn.asc"), overwrite=TRUE)
  writeRaster(x = br_ht, gdal="COMPRESS=NONE",
              filename = paste0(path, "/br_ht/plot",
                                plot_number, "/br_ht.asc"), overwrite=TRUE)
  # writeRaster(x = dnd_db, gdal="COMPRESS=NONE",
  #             filename = paste0(path, "/dnd_db/plot",
  #                               plot_number, "/dnd_db.asc"), overwrite=TRUE)
  writeRaster(x = dnd_st, gdal="COMPRESS=NONE",
              filename = paste0(path, "/dnd_st/plot",
                                plot_number, "/dnd_st.asc"), overwrite=TRUE)
  writeRaster(x = fb_dn, gdal="COMPRESS=NONE",
              filename = paste0(path, "/fb_dn/plot",
                                plot_number, "/fb_dn.asc"), overwrite=TRUE)
  writeRaster(x = rk_dn, gdal="COMPRESS=NONE",
              filename = paste0(path, "/rk_dn/plot",
                                plot_number, "/rk_dn.asc"), overwrite=TRUE)
  writeRaster(x = dnd_stc, gdal="COMPRESS=NONE",
              filename = paste0(path, "/dnd_stc/plot",
                                plot_number, "/dnd_stc.asc"), overwrite=TRUE)
  
  ## ========================================
  ##            Export Geo Rasters       ----
  ## ========================================
  
  # export elevation raster ----
  writeRaster(x = elev, gdal="COMPRESS=NONE",
              filename = paste0(path, "/elev/plot",
                                plot_number, "/elev.asc"), overwrite=TRUE)
  
  # export heat load raster ----
  writeRaster(x = hli, gdal="COMPRESS=NONE",
              filename = paste0(path, "/hli/plot",
                                plot_number, "/hli.asc"), overwrite=TRUE)
  
  # export slope raster ----
  writeRaster(x = slope, gdal="COMPRESS=NONE",
              filename = paste0(path, "/slope/plot",
                                plot_number, "/slope.asc"), overwrite=TRUE)
}
```

## Save New Rasters for All Plots

```{r}
for (i in seq(1:8)) {
  createPredStack(plot_number = i,
                  path = output_dir)
}
```





