---
title: "Maxent for Slimy Salamander"
subtitle: "Plot 1"
author: "Briana Barajas"
date: "`r Sys.Date()`"
---
```{r set-up, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```

```{r packages, include=FALSE}
# wrangling
library(tidyverse)
library(here)
library(janitor)

# raster/geospatial
library(sf)
library(tmap)
library(terra)
library(raster)
library(spatialEco) #transform elev to hli

# modeling
library(dismo)
library(rsample)
library(rJava)
```

## Read in Data

```{r read}
## ========================================
##            Vector Data              ----
## ========================================

# species point data
occurence_p1 <- st_read(here('data/CampRoberts_spatial_data/Species_pts/CR_BASP_obs_11Jul22.shp')) %>% 
  clean_names() %>% 
  st_make_valid() %>% 
  filter(plot == 1)

# plot outline
outline_p1 <- st_read(here("data", "CampRoberts_spatial_data", 
                           "plot_outlines", "Plot_1.shp")) %>% 
  st_make_valid() 

## ========================================
##         Geomorphology Rasters       ----
## ========================================

# elevation and slope rasters
slope <- rast('data/CampRoberts_spatial_data/crob_slope')
elev <- rast('data/CampRoberts_spatial_data/crob_elev')

# create hli raster
hli <-  hli(elev)

## ========================================
##            Vegetation Rasters       ----
## ========================================

# load canopy raster
canopy_p1 <- rast(here("data", "CampRoberts_spatial_data", "Canopy_raster",
                       "can_fx_3r_p1"))

# load downed wood cover
dnd_dn_p1 <- rast(here("data", "CampRoberts_spatial_data", "brush_IDW3rad",
                       "3rd_dnd_dn_p1"))

# load litter cover percentage
li_dn_p1 <- rast(here("data", "CampRoberts_spatial_data", "brush_IDW3rad",
                      "3rd_li_dn_p1"))

# load grass cover
gs_dn_p1 <- rast(here("data", "CampRoberts_spatial_data", "brush_IDW3rad",
                      "3rd_gs_dn_p1"))

```

## Reproject Data

```{r reproject}
## ========================================
##            Vector Data              ----
## ========================================

# occurence points
occurence_p1 <- st_transform(occurence_p1, crs = "WGS84") 

# plot outlines
outline_p1 <- st_transform(outline_p1, crs = "WGS84")

# plot together to see if points fall outside of plot
tm_shape(outline_p1) +
  tm_polygons() +
  tm_shape(occurence_p1) +
  tm_dots()

## ========================================
##         Geomorphology Rasters       ----
## ========================================

# reproject elevation and slope raster
elev <- project(elev, y = "WGS84")
slope <- project(slope, y = "WGS84")

# create hli raster using reprojected elevation
hli <- hli(elev)

# # plot geo rast w/occurence points
# tm_shape(slope) +
#   tm_raster() +
#   tm_shape(outline_p1) +
#   tm_borders(col = "black") +
#   tm_shape(occurence_p1) +
#   tm_dots(size = 0.3)
  

## ========================================
##            Vegetation Rasters       ----
## ========================================
canopy_p1 <- project(x = canopy_p1, y = "WGS84")
dnd_dn_p1 <- project(x = dnd_dn_p1, y = "WGS84")
li_dn_p1 <- project(x = li_dn_p1, y = "WGS84")
gs_dn_p1 <- project(x = gs_dn_p1, y = "WGS84")

# # plot a vegetation rast w/ occurence points
# tm_shape(canopy_p1) +
#   tm_raster() +
#   tm_shape(outline_p1) +
#   tm_borders(col = "black") +
#   tm_shape(occurence_p1) +
#   tm_dots(size = 0.3)
```


## Prep Rasters for Maxent

```{r res, eval=FALSE}
## ========================================
##        Count NAs in Rasters         ----
## ========================================
# check NAs in vegetation rasters
global(canopy_p1, fun="isNA")
global(dnd_dn_p1, fun="isNA")
global(li_dn_p1, fun="isNA")
global(gs_dn_p1, fun="isNA")

# check NAs in geo rasters
global(elev, fun="isNA") #217986
global(hli, fun="isNA") #223402
global(slope, fun="isNA") #223139

## ========================================
##        Combine & Update Extent      ----
## ========================================
# create raster stack for vegetation
veg_stack <- c(canopy_p1, dnd_dn_p1, li_dn_p1, gs_dn_p1)

# create raster stack for
geo_stack <- c(elev, hli, slope)

# compare extents
ext(veg_stack) < ext(geo_stack)

# crop geo_stack to match extent of veg_stack
ext(geo_stack) <- c(-120.831276592031, -120.827739307194, 35.7446884285381, 35.7476193216885)


## ========================================
##       Update Resolution & Stack     ----
## ========================================
# lower resolution in all geomorphic layers
res(geo_stack) <- res(veg_stack) # RETURNS BLANK RASTER

# stack all layers
predictor_stack <- c(veg_stack, geo_stack)
```


## Running Maxent
```{r maxent}
# convert predictors to raster object
canopy_p1 <- raster(canopy_p1)
dnd_dn_p1 <- raster(dnd_dn_p1)
li_dn_p1 <- raster(li_dn_p1)
gs_dn_p1 <- raster(gs_dn_p1)

# create raster stack
veg_test_stack <- raster::stack(canopy_p1, dnd_dn_p1,
                                li_dn_p1, gs_dn_p1)

# convert occurence from sf to sp
occurence_p1_sp <- as_Spatial(occurence_p1)

# maxent mode, only vegetation layers
maxent(veg_test_stack, occurence_p1_sp,
       removeDuplicates=TRUE)
```










