---
title: "Creating Prediction Rasters for All Plots"
subtitle: "MaxEnt with rasters cropped to plot outline"
author: "Briana Barajas"
date: 2024-03-11
---

## Preparation

```{r set-up, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```

Read in libraries 
```{r packages, eval=FALSE}
# wrangling
library(tidyverse)
library(here)
library(janitor)

# raster/geospatial
library(sf)
library(tmap)
library(terra)
library(raster)
library(spatialEco) #transform elev to hli

# modeling
library(dismo)
library(rsample)
library(rJava)

# set data directory
data_dir <- here("data", "CampRoberts_spatial_data")
```

Source maxent function
```{r, results='hide'}
# source maxent file function
source(knitr::purl(here("dismo-crop-plot-maxent", "crop-plot-maxent-function.Rmd")))
```

## Maxent Predictions 


```{r}
# create list of plot outline shape files
plot_outline_files <- list.files(here::here("data", "CampRoberts_spatial_data", "plot_outlines"), pattern = "\\.shp$", full.names = TRUE)

# for-loop to read in data
for (i in seq_along(plot_outline_files)) {
  
  # read in data
  outline <- st_read(plot_outline_files[i])
  
  # update CRS
  outline <- st_transform(outline, "WGS84")
  
  # save to global environment
  assign(paste0("outline_p", i), outline, envir = .GlobalEnv)
  
}
```

```{r}
# read in all occurence points
for (i in 1:8) {
  
  occurence <- st_read(here(data_dir, "Species_pts",
                            "CR_BASP_obs_11Jul22.shp")) %>% 
    clean_names() %>% 
    st_make_valid() %>% 
    filter(plot == i)
  
  occurence <- st_transform(occurence, "WGS84")
  
  assign(x = paste0("occurence_p", i), value = occurence,
         envir = .GlobalEnv)
}

```


## Create prediction maps

Run maxent and create predictions for all plots
```{r}
## ......................Plot 1....................
maxent_p1 <- slsa_crop_maxent(plot_number = 1, new_crs = "WGS84")
pred_map_p1 <- predict(maxent_p1, pred_stack_rast_p1)

## ......................Plot 2....................
maxent_p2 <- slsa_crop_maxent(plot_number = 2, new_crs = "WGS84")
pred_map_p2 <- predict(maxent_p2, pred_stack_rast_p2)

## ......................Plot 3....................
maxent_p3 <- slsa_crop_maxent(plot_number = 3, new_crs = "WGS84")
pred_map_p3 <- predict(maxent_p3, pred_stack_rast_p3)

## ......................Plot 4....................
maxent_p4 <- slsa_crop_maxent(plot_number = 4, new_crs = "WGS84")
pred_map_p4 <- predict(maxent_p4, pred_stack_rast_p4)

## ......................Plot 5....................
maxent_p5 <- slsa_crop_maxent(plot_number = 5, new_crs = "WGS84")
pred_map_p5 <- predict(maxent_p5, pred_stack_rast_p5)

## ......................Plot 6....................
maxent_p6 <- slsa_crop_maxent(plot_number = 6, new_crs = "WGS84")
pred_map_p6 <- predict(maxent_p6, pred_stack_rast_p6)

## ......................Plot 7....................
maxent_p7 <- slsa_crop_maxent(plot_number = 7, new_crs = "WGS84")
pred_map_p7 <- predict(maxent_p7, pred_stack_rast_p7)

## ......................Plot 8....................
maxent_p8 <- slsa_crop_maxent(plot_number = 8, new_crs = "WGS84")
pred_map_p8 <- predict(maxent_p8, pred_stack_rast_p8)

```



Plot prediction rasters
```{r}
## ......................Plot 1....................
tm_shape(pred_map_p1) +
  tm_raster() +
  tm_title(text = "Plot 1 Suitability") +
  tm_shape(outline_p1) +
  tm_borders() +
  tm_shape(occurence_p1) +
  tm_dots()

# tmap_save(tm = mp_1, filename = here("outputs", "crop-area-maxent",
#                             "prediction_maps", "plot_1_predict.png"))

## ......................Plot 2....................
tm_shape(pred_map_p2) +
  tm_raster() +
  tm_title(text = "Plot 2 Suitability") +
  tm_shape(outline_p2) +
  tm_borders() +
  tm_shape(occurence_p2) +
  tm_dots()

# tmap_save(tm = mp_2, filename = here("outputs", "crop-area-maxent",
#                             "prediction_maps", "plot_2_predict.png"))

## ......................Plot 3....................
tm_shape(pred_map_p3) +
  tm_raster() +
  tm_title(text = "Plot 3 Suitability") +
  tm_shape(outline_p3) +
  tm_borders() +
  tm_shape(occurence_p3) +
  tm_dots()

# tmap_save(tm = mp_3, filename = here("outputs", "crop-area-maxent",
#                             "prediction_maps", "plot_3_predict.png"))

## ......................Plot 4....................
tm_shape(pred_map_p4) +
  tm_raster() +
  tm_title(text = "Plot 4 Suitability") +
  tm_shape(outline_p4) +
  tm_borders() +
  tm_shape(occurence_p4) +
  tm_dots()

# tmap_save(mp_4, filename = here("outputs", "crop-area-maxent",
#                             "prediction_maps", "plot_4_predict.png"))

## ......................Plot 5....................
tm_shape(pred_map_p5) +
  tm_raster() +
  tm_title(text = "Plot 5 Suitability") +
  tm_shape(outline_p5) +
  tm_borders() +
  tm_shape(occurence_p5) +
  tm_dots()

# tmap_save(mp_5, filename = here("outputs", "crop-area-maxent",
#                             "prediction_maps", "plot_5_predict.png"))

## ......................Plot 6....................
tm_shape(pred_map_p6) +
  tm_raster() +
  tm_title(text = "Plot 6 Suitability") +
  tm_shape(outline_p6) +
  tm_borders() +
  tm_shape(occurence_p6) +
  tm_dots()

# tmap_save(mp_6, filename = here("outputs", "crop-area-maxent",
#                             "prediction_maps", "plot_6_predict.png"))

## ......................Plot 7....................
tm_shape(pred_map_p7) +
  tm_raster() +
  tm_title(text = "Plot 7 Suitability") +
  tm_shape(outline_p7) +
  tm_borders() +
  tm_shape(occurence_p7) +
  tm_dots()

# tmap_save(mp_7, filename = here("outputs", "crop-area-maxent",
#                             "prediction_maps", "plot_7_predict.png"))

## ......................Plot 8....................
tm_shape(pred_map_p8) +
  tm_raster() +
  tm_title(text = "Plot 8 Suitability") +
  tm_shape(outline_p8) +
  tm_borders() +
  tm_shape(occurence_p8) +
  tm_dots()

# tmap_save(mp_8, filename = here("outputs", "crop-area-maxent",
#                             "prediction_maps", "plot_8_predict.png"))
```
