---
title: "Using SDMtune to Tune MaxEnt"
subtitle: "Plot 1 - Tuning Defaults from Example Code"
author: "Briana Barajas"
date: 2024-03-12
---

```{r}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```

```{r packages, include=FALSE}
# wrangling
library(tidyverse)
library(here)
library(janitor)

# raster/geospatial
library(sf)
library(tmap)
library(terra)

# modeling
library(SDMtune)
library(rsample)
library(rJava)

# set data directory
output_dir <- here("data", "updated-rasters")
data_dir <- here("data", "CampRoberts_spatial_data")

# set plot number
plot_name <- "plot4"
plot_number <- 4
```


## Read in Data

```{r, results='hide'}
# read environmental rasters
canopy <- rast(here(output_dir, "canopy", plot_name, "canopy.asc"))
dnd_dn <- rast(here(output_dir, "dnd_dn", plot_name, "dnd_dn.asc"))
elev <- rast(here(output_dir, "elev", plot_name, "elev.asc"))
gs_dn <- rast(here(output_dir, "gs_dn", plot_name, "gs_dn.asc"))
hli <- rast(here(output_dir, "hli", plot_name, "hli.asc"))
li_dn <- rast(here(output_dir, "li_dn", plot_name, "li_dn.asc"))
slope <- rast(here(output_dir, "slope", plot_name, "slope.asc"))


# combine environmental rasters
predictor_stack_rast <- c(elev, hli, slope, canopy, dnd_dn, li_dn, gs_dn)

# read in occurrence data
occurrences <- st_read(here(data_dir, "Species_pts", "CR_BASP_obs_11Jul22.shp")) %>% 
  st_make_valid() %>% 
  clean_names() %>% 
  filter(plot == plot_number)
```

## Running Maxent

```{r}
# isolate occurrence latitude and longitude
p_coords <- occurrences %>% 
  st_drop_geometry() %>% 
  rename(y = latitude,
         x = longitude) %>% 
    dplyr::select(x,y)

# calculat number of points
num_bg <- 10 * length(occurrences)

# create background points using raster stack
bg_points <- terra::spatSample(predictor_stack_rast,
                               size = 1000,
                               replace = FALSE,
                               xy = TRUE)

bg_coords <- bg_points %>% dplyr::select(c(x,y))

# create SWD object
swd_object <- prepareSWD(species = "slender salamander",
                         p = p_coords,
                         a = bg_coords,
                         env = predictor_stack_rast)

# split data into test and train
datasets <- trainValTest(swd_object, test = 0.2, 
                         only_presence = TRUE, seed = 25)
train <- datasets[[1]]
test <- datasets[[2]]

# train maxent model
maxnet_model <- train(method = "Maxnet", data = train)

# select the hyperparameters to test
h_tune <- list(reg = seq(0.1, 3, 0.1), 
               fc = c("lq", "lh", "lqp", "lqph", "lqpht"))

# test all the possible combinations with gridSearch
gs <- gridSearch(maxnet_model, 
                 hypers = h_tune, 
                 metric = "auc", 
                 test = test)

# view results of top performing models
head(gs@results[order(-gs@results$test_AUC), ])  

# view parameters of best model
gs@models[[1]]


# # Use the genetic algorithm instead with optimizeModel
# om <- optimizeModel(maxnet_model, hypers = h_tune, 
#                     metric = "auc", test = test, seed = 4)
# 
# head(om@results)  # Best combinations
```

## Creating predictions
```{r}
# create prediction raster
map <- predict(maxnet_model,
               data = predictor_stack_rast,
               type = "cloglog")

# plot prediction map
tm_shape(map) +
  tm_raster() +
  tm_shape(outline_p1) +
  tm_borders() +
  tm_shape(occurrence_p1) +
  tm_dots()
```


