---
title: "Using SDMtune to Tune MaxEnt"
subtitle: "Plot 1"
author: "Briana Barajas"
date: "`r Sys.Date()`"
---

```{r set-up, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```

```{r packages, include=FALSE}
# wrangling
library(tidyverse)
library(here)
library(janitor)

# raster/geospatial
library(sf)
library(tmap)
library(terra)
library(raster)
library(spatialEco) #transform elev to hli

# modeling
library(SDMtune)
library(rsample)
library(rJava)

# set data directory
data_dir <- here("data", "CampRoberts_spatial_data")
```

## Read in Data

```{r read}
## ========================================
##            Vector Data              ----
## ========================================

# species point data
occurence_p1 <- st_read(here(data_dir, "Species_pts", "CR_BASP_obs_11Jul22.shp")) %>% 
  clean_names() %>% 
  st_make_valid() %>% 
  filter(plot == 1)

# plot outline
outline_p1 <- st_read(here(data_dir, "plot_outlines", "Plot_1.shp")) %>% 
  st_make_valid() 

## ========================================
##         Geomorphology Rasters       ----
## ========================================

# elevation and slope rasters
slope <- rast(here(data_dir, "old", "crob_slope"))
elev <- rast(here(data_dir, "crob_elev"))

# create hli raster
hli <-  hli(elev)

## ========================================
##            Vegetation Rasters       ----
## ========================================

# load canopy raster
canopy_p1 <- rast(here(data_dir, "Canopy_raster", "can_fx_3r_p1"))

# load downed wood cover
dnd_dn_p1 <- rast(here(data_dir, "brush_IDW3rad", "3rd_dnd_dn_p1"))

# load litter cover percentage
li_dn_p1 <- rast(here(data_dir, "brush_IDW3rad", "3rd_li_dn_p1"))

# load grass cover
gs_dn_p1 <- rast(here(data_dir, "brush_IDW3rad", "3rd_gs_dn_p1"))

```

## Reproject Data

```{r reproject}
## ========================================
##            Vector Data              ----
## ========================================

# occurence points
occurence_p1 <- st_transform(occurence_p1, crs = "WGS84") 

# plot outlines
outline_p1 <- st_transform(outline_p1, crs = "WGS84")

# plot together to see if points fall outside of plot
tm_shape(outline_p1) +
  tm_polygons() +
  tm_shape(occurence_p1) +
  tm_dots()

## ========================================
##         Geomorphology Rasters       ----
## ========================================

# reproject elevation and slope raster
elev <- project(elev, y = "WGS84")
slope <- project(slope, y = "WGS84")

# create hli raster using reprojected elevation
hli <- project(hli, y = "WGS84")

# # plot geo rast w/occurence points
# tm_shape(slope) +
#   tm_raster() +
#   tm_shape(outline_p1) +
#   tm_borders(col = "black") +
#   tm_shape(occurence_p1) +
#   tm_dots(size = 0.3)
  

## ========================================
##            Vegetation Rasters       ----
## ========================================
canopy_p1 <- project(x = canopy_p1, y = "WGS84")
dnd_dn_p1 <- project(x = dnd_dn_p1, y = "WGS84")
li_dn_p1 <- project(x = li_dn_p1, y = "WGS84")
gs_dn_p1 <- project(x = gs_dn_p1, y = "WGS84")

# plot a vegetation rast w/ occurence points
tm_shape(canopy_p1) +
  tm_raster() +
  tm_shape(outline_p1) +
  tm_borders(col = "black") +
  tm_shape(occurence_p1) +
  tm_dots(size = 0.3)

## ========================================
##           Update Raster Names       ----
## ========================================
set.names(elev, "elevation")
set.names(hli, "heat_load_index")
set.names(slope, "slope")
set.names(canopy_p1, "canopy_cover")
set.names(dnd_dn_p1, "downed_wood_cover")
set.names(li_dn_p1, "litter_cover")
set.names(gs_dn_p1, "grass_cover")
```


## Prep Rasters for Maxent

```{r res}
## ========================================
##             Update Extent           ----
## ========================================
# store extent of smaller vegetation rasters
can_extent <- ext(canopy_p1)

# crop geo rasters
elev <- crop(elev, canopy_p1)
hli <- crop(hli, canopy_p1)
slope <- crop(slope, canopy_p1)

# update extent of geo rasters
ext(elev) <- c(can_extent$xmin, can_extent$xmax,
               can_extent$ymin, can_extent$ymax)
ext(hli) <- c(can_extent$xmin, can_extent$xmax,
               can_extent$ymin, can_extent$ymax)
ext(slope) <- c(can_extent$xmin, can_extent$xmax,
               can_extent$ymin, can_extent$ymax)

## ========================================
##        Count NAs in Rasters         ----
## ========================================
# # check NAs in vegetation rasters
# global(canopy_p1, fun="isNA")
# global(dnd_dn_p1, fun="isNA")
# global(li_dn_p1, fun="isNA")
# global(gs_dn_p1, fun="isNA")
# 
# # check NAs in geo rasters
# global(elev, fun="isNA") #74043
# global(hli, fun="isNA") #77125
# global(slope, fun="isNA") #223139

## ========================================
##         Update Resolutions         ----
## ========================================
# update resolution in all geomorphic layers
elev <- resample(elev, canopy_p1)
hli <- resample(hli, canopy_p1)
slope <- resample(slope, canopy_p1)

```


## Running Maxent

```{r}
# isolate occurence latitude and longitude
p_coords <- occurence_p1 %>% 
  st_drop_geometry() %>% 
  rename(y = latitude,
         x = longitude) %>% 
    dplyr::select(x,y)

# combine environmental rasters
predictor_stack_rast <- c(elev, hli, slope, canopy_p1, dnd_dn_p1, li_dn_p1, gs_dn_p1)

# create background points using raster stack
bg_points <- terra::spatSample(predictor_stack_rast,
                               size = 1000,
                               replace = FALSE,
                               xy = TRUE)

bg_coords <- bg_points %>% dplyr::select(c(x,y))

# create SWD object
swd_object <- prepareSWD(species = "slender salamander",
                         p = p_coords,
                         a = bg_coords,
                         env = predictor_stack_rast)

# split data into test and train
datasets <- trainValTest(swd_object, test = 0.2, only_presence = TRUE, seed = 25)
train <- datasets[[1]]
test <- datasets[[2]]

# train maxent model
maxnet_model <- train(method = "Maxnet", data = train)

# select the hyperparameters to test
h_tune <- list(reg = seq(0.1, 3, 0.1), fc = c("lq", "lh", "lqp", "lqph", "lqpht"))

# test all the possible combinations with gridSearch
gs <- gridSearch(maxnet_model, 
                 hypers = h_tune, 
                 metric = "auc", 
                 test = test)

head(gs@results[order(-gs@results$test_AUC), ])  # Best combinations

# Use the genetic algorithm instead with optimizeModel
om <- optimizeModel(maxnet_model, hypers = h_tune, 
                    metric = "auc", test = test, seed = 4)

head(om@results)  # Best combinations
```

## Creating predictions
```{r}
# create prediction raster
map <- predict(maxnet_model,
               data = predictor_stack_rast,
               type = "cloglog")

# plot prediction map
tm_shape(map) +
  tm_raster() +
  tm_shape(outline_p1) +
  tm_borders() +
  tm_shape(occurence_p1) +
  tm_dots()
```


